apiVersion: apps/v1
kind: Deployment
metadata:
  name: healio-deployment
  labels:
    app: healio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healio
  template:
    metadata:
      labels:
        app: healio
    spec:
      containers:
        - name: healio-backend
          image: sujitkumarvipul/healio:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "YOUR_CLEVER_CLOUD_HOST"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "YOUR_DATABASE_NAME"
            - name: DB_USER
              value: "YOUR_DATABASE_USER"
            - name: DB_PASSWORD
              value: "YOUR_DATABASE_PASSWORD" # Completely safe placeholder
            - name: KAFKA_HOST
              value: "YOUR_CONFLUENT_CLOUD_HOST"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_PROTOCOL
              value: "SASL_SSL"
            - name: KAFKA_MECHANISM
              value: "PLAIN"
            - name: KAFKA_USER
              value: "YOUR_KAFKA_API_KEY"
            - name: KAFKA_PASS
              value: "YOUR_KAFKA_API_SECRET"