apiVersion: v1
kind: Service
metadata:
  name: healio-service
spec:
  type: LoadBalancer # Requests a cloud provider load balancer to route traffic from the internet
  selector:
    app: healio # Matches the label defined in our deployment pods
  ports:
    - protocol: TCP
      port: 80       # The public port exposed to the outside internet
      targetPort: 8080 # The internal port your Spring Boot container listens on