apiVersion: v1
kind: Service
metadata:
  name: healio-service
spec:
  type: NodePort # FIXED: Changed from LoadBalancer to NodePort to work on a single EC2 instance
  selector:
    app: healio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # FIXED: Explicitly maps the incoming traffic from AWS port 30080